on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "demo-service-account@eddiezane-no-trust-demo.iam.gserviceaccount.com"
      - uses: 'google-github-actions/setup-gcloud@v1'
      - name: whoami
        run: gcloud auth list
